### ISSUE TITLE
Poznámky

### ISSUE THREAD

**Issue by klepo** [5G-ERA/Reference-NetApp#10]
- Pokud se ukončí klient natvrdo (SIGKILL), tak zůstane v interface obsazený port, a také možná zůstanou viset nějaký vlákna
- Až skončí video, bylo by asi dobré odregistrovat se.
- Celkově asi nejsou otestovány a vyřešeny situace, kdy něco spadne, přeruší se spojení nebo něco zůstane viset.
- Pokud jede klient i NetApp, pak se NetApp a znovu zapne, tak se klient asi neodpojí a snaží se stále připojit.
- Port pro socketio by měl být parametrizovatelný (při spouštění NetApp), a také by měl jít získat z middleware (pokud se používá), stejně jako je teď získána adresa. Teď je u klienta v kódu natvrdo.
- U příkladů klienta ("test_client_*") chcete např. cestu k testovacímu videu nastavit přes enviromentální proměnné. S tím ve finální verzi nemám problém, ale nechal bych tam nějaké záložní defaultní nastavení, aby to prostě nějak fungovalo hned po stažení z gitu a instalaci balíčků. Přijde mi otravné pro první spuštění zkoumat, jaké musím nastavit proměnné. Pokud by to mělo být uloženo v env proměnných, tak bych tam dal i podobné věci, jako IP, login, heslo, task_id, ale také cesty ke configu sítí yolo, mask_rcnn apod. (ty jsou tam teď také natvrdo). Možná by bylo dobré udělat místo env proměnných možná nějaký konfigurační soubor. Pěkné by to bylo na jednom místě.
- Vypadá to, že do requirements se budou ještě muset přidat balíčky pro mmdet, mmvc apod., ale k prozkoumání těchto zdrojáků jsem se ještě pořádně nedostal.
- Pokud se aktuální kódy mají dále využívat pro jiné NetApp a balit do balíčků, tak za mě by to chtělo určitě ještě alespoň jednou tolik okomentovat nebo lépe pojmenovat některé proměnné a prostě trochu více učesat. Těmi kódy procházím už několik dnů, mám toho plnou hlavu a rozklíčovat fungování některých částí je celkem peklo.

**Comment by Kapim** [comment]
> Pokud se ukončí klient natvrdo (SIGKILL), tak zůstane v interface obsazený port, a také možná zůstanou viset nějaký vlákna
> Až skončí video, bylo by asi dobré odregistrovat se.

založím na to issue a můžeme to opravit / upravit
> Celkově asi nejsou otestovány a vyřešeny situace, kdy něco spadne, přeruší se spojení nebo něco zůstane viset.

to nejsou, je čas se na to teď zaměřit a odchytat to
> Pokud jede klient i NetApp, pak se NetApp a znovu zapne, tak se klient asi neodpojí a snaží se stále připojit.

Ano, asi bude potřeba nějak sledovat stav websocketu nebo možná dodělat nějaký heartbeat a udělat logiku znovunavázání spojení
> Port pro socketio by měl být parametrizovatelný (při spouštění NetApp), a také by měl jít získat z middleware (pokud se používá), stejně jako je teď získána adresa. Teď je u klienta v kódu natvrdo.

určitě
> U příkladů klienta ("test_client_*") chcete např. cestu k testovacímu videu nastavit přes enviromentální proměnné. S tím ve finální verzi nemám problém, ale nechal bych tam nějaké záložní defaultní nastavení, aby to prostě nějak fungovalo hned po stažení z gitu a instalaci balíčků. Přijde mi otravné pro první spuštění zkoumat, jaké musím nastavit proměnné. Pokud by to mělo být uloženo v env proměnných, tak bych tam dal i podobné věci, jako IP, login, heslo, task_id, ale také cesty ke configu sítí yolo, mask_rcnn apod. (ty jsou tam teď také natvrdo). Možná by bylo dobré udělat místo env proměnných možná nějaký konfigurační soubor. Pěkné by to bylo na jednom místě.

Defaultní nastavení nedává smysl, protože client bude v odděleném repozitáři a bude obecný pro všechny NetApps. Smysl to bude dávat jen v tom případě, že nachystáme example který bude pouze pro referenční NetApp a bude v jejím repozitáři / balíčku. Tam pak dává smysl nastavit na tvrdo task_id i cestu k videu. IP, login a heslo by určitě neměly být uloženy v gitu. Cesty ke configu sítí jsou už teď nastaveny pomocí env proměnných

> Vypadá to, že do requirements se budou ještě muset přidat balíčky pro mmdet, mmvc apod., ale k prozkoumání těchto zdrojáků jsem se ještě pořádně nedostal.

Nevím jistě jestli to tam dodávat, protože ta referenční netapp se dá spustit i s alternativním detektorem - opencv a dummyfps a potom nesou mmcv ani mmdet potřeba... Pro rychlé vyzkoušení je pak není potřeba instalovat, takže bych je udělal optional (ale nevím jistě jak se to v pythonu dělá)

> Pokud se aktuální kódy mají dále využívat pro jiné NetApp a balit do balíčků, tak za mě by to chtělo určitě ještě alespoň jednou tolik okomentovat nebo lépe pojmenovat některé proměnné a prostě trochu více učesat. Těmi kódy procházím už několik dnů, mám toho plnou hlavu a rozklíčovat fungování některých částí je celkem peklo.

uvítám jakékoliv návrhy, ideálně formou pull requestu

**Comment by ZdenekM** [comment]
Borci, jen technická poznámka - neměli bysme tedy ty issues psát anglicky - sice jen teoreticky, ale mohl by to tady číst někdo z partnerů, případně třeba i vytvářet nová issues? Ale jinak tohle jsou spíš témata někam do interní diskuze, než na veřejné repo :-)

**Comment by ZdenekM** [comment]
Ha, dívám se že ostatní issues jsou anglicky... Tak jen toto bych navrhoval přenést do nějakého interního prostoru...

**Comment by klepo** [comment]
Zdar, tohle byl jen rychlý soupis myšlenek, které jsem měl v pátek v hlavě.
Nechtěl jsem na ně zapomenout, tak jsem to napsal tímto způsobem. Byl to
takový návrh na jednotlivé issues, s tím, že počkám na ostatní, zda to dává
smysl. Česky to asi vysvětlím lépe. Ale ať jsou issues anglicky, nemám s
tím problém.

Dne po 20. 2. 2023 9:55 uživatel Zdeněk Materna ***@***.***>
napsal:
