### ISSUE TITLE
Move test video and test image to era-5g-client repo?

### ISSUE THREAD

**Issue by idobes** [5G-ERA/Reference-NetApp#24]
May be the test video and the test image from assets dir should be moved to the separate client repository (era-5g-client), so that it is together with the client code?

**Comment by Kapim** [comment]
I think the test data should stick with the NetApp because they are specific for the Reference-Netapp, while the client is general for all net apps.

**Comment by idobes** [comment]
Ok, I agree. Then maybe we should think about moving the codes from 5G-ERA/era_5g_client/scripts back to this repository, because these are specific for the Reference-Netapp as well..?

**Comment by Kapim** [comment]
In my opinion, we should have some "general" example scripts which should be placed in the era-5g-client repository (probably somehow generalized testing scripts we have now) and also some example clients which should be placed alongside the Reference NetApp in this repository.

**Comment by Kapim** [comment]
General examples moved to https://github.com/5G-ERA/era-5g-client, ReferenceNetapp-specific examples placed in /examples/python folder.
